// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnCZ7nxWsHAcdzo-y7cI5a42htHWQKWfc',
    appId: '1:62598723004:web:83752f5f8b6877547827b9',
    messagingSenderId: '62598723004',
    projectId: 'findlink-449810',
    authDomain: 'findlink-449810.firebaseapp.com',
    storageBucket: 'findlink-449810.firebasestorage.app',
    measurementId: 'G-8YQLN74HG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcDsni5o5H8mHA5njDdZkTKt-FZGMIuZc',
    appId: '1:62598723004:android:794857e4447fc6bc7827b9',
    messagingSenderId: '62598723004',
    projectId: 'findlink-449810',
    storageBucket: 'findlink-449810.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAQ0m93A768HH7SBzfwlyv3FFSNfy3e-g',
    appId: '1:62598723004:ios:2acb78953732f7527827b9',
    messagingSenderId: '62598723004',
    projectId: 'findlink-449810',
    storageBucket: 'findlink-449810.firebasestorage.app',
    iosBundleId: 'com.example.findlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAQ0m93A768HH7SBzfwlyv3FFSNfy3e-g',
    appId: '1:62598723004:ios:2acb78953732f7527827b9',
    messagingSenderId: '62598723004',
    projectId: 'findlink-449810',
    storageBucket: 'findlink-449810.firebasestorage.app',
    iosBundleId: 'com.example.findlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnCZ7nxWsHAcdzo-y7cI5a42htHWQKWfc',
    appId: '1:62598723004:web:58f14323f115d95e7827b9',
    messagingSenderId: '62598723004',
    projectId: 'findlink-449810',
    authDomain: 'findlink-449810.firebaseapp.com',
    storageBucket: 'findlink-449810.firebasestorage.app',
    measurementId: 'G-PPD4LWYM4Z',
  );
}
