// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJgw142ugimVb30QUotOqYe_RYmzXgXMg',
    appId: '1:677216091931:web:8087349c7f8b1f30525dbe',
    messagingSenderId: '677216091931',
    projectId: 'missingperson-345a8',
    authDomain: 'missingperson-345a8.firebaseapp.com',
    storageBucket: 'missingperson-345a8.firebasestorage.app',
    measurementId: 'G-M315Z50CS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSgZdfTtAzH9sgyp5kpcxAq1BXflMryqU',
    appId: '1:677216091931:android:b29e2f38e3f61359525dbe',
    messagingSenderId: '677216091931',
    projectId: 'missingperson-345a8',
    storageBucket: 'missingperson-345a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBya3YTLVWGGmVnKcxJ-tPQkBBu2DHjlHw',
    appId: '1:677216091931:ios:a33ebdc939ee66ce525dbe',
    messagingSenderId: '677216091931',
    projectId: 'missingperson-345a8',
    storageBucket: 'missingperson-345a8.firebasestorage.app',
    iosClientId: '677216091931-nj3n1k5hf7o79r6s0p7o1h3evnreq9q7.apps.googleusercontent.com',
    iosBundleId: 'com.example.findlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBya3YTLVWGGmVnKcxJ-tPQkBBu2DHjlHw',
    appId: '1:677216091931:ios:a33ebdc939ee66ce525dbe',
    messagingSenderId: '677216091931',
    projectId: 'missingperson-345a8',
    storageBucket: 'missingperson-345a8.firebasestorage.app',
    iosClientId: '677216091931-nj3n1k5hf7o79r6s0p7o1h3evnreq9q7.apps.googleusercontent.com',
    iosBundleId: 'com.example.findlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJgw142ugimVb30QUotOqYe_RYmzXgXMg',
    appId: '1:677216091931:web:05e1da98a439e26a525dbe',
    messagingSenderId: '677216091931',
    projectId: 'missingperson-345a8',
    authDomain: 'missingperson-345a8.firebaseapp.com',
    storageBucket: 'missingperson-345a8.firebasestorage.app',
    measurementId: 'G-QBD9E7376M',
  );

}